### PR TITLE
CSS + HTML Cleanup.

### PR DESCRIPTION
**Pull request by AndrewCEmil**
* Cleaned up CSS
* Cleaned up HTML
* Cleaned up some JS
* Fixed issue with aspect ratio.

### CODE REVIEW

**Review by CharStiles — APPROVED** [review]
This looks great!! love all the organization and changes to the css. Thank you <3

**Comment by AndrewCEmil** [comment]
I resolved the commits using the github ui. I'm a little unsure on how to pull them and test them. Want to just merge them and then I can test locally and fix any problems?

**Comment by CharStiles** [comment]
merging now! Thanks.

**Comment by CharStiles** [comment]
IDK if this would have helped but I use github command line tools to test branches when you install them, you can type `gh pr checkout 13` and it checks out the branch

**Pull request merged**
